In [2]:
import pandas_datareader.data as web # pandas-datareaderのインポート
import requests
import pandas as pd
import yfinance as yf

In [4]:
url_PL = 'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol={}&apikey={}'.format(symbol,api_key)
url_BS = 'https://www.alphavantage.co/query?function=BALANCE_SHEET&symbol={}&apikey={}'.format(symbol,api_key)
url_CF = 'https://www.alphavantage.co/query?function=CASH_FLOW&symbol={}&apikey={}'.format(symbol,api_key)
url_EPS = 'https://www.alphavantage.co/query?function=EARNINGS&symbol={}&apikey={}'.format(symbol,api_key)

NameError: name 'symbol' is not defined

In [8]:
api_key='SRG6H2AQ57H9PSQ4'

In [48]:
pl_japa=['収益','営業利益','EBITDA','純利益']
def FR(symbol,api_key):
    url='https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol='+symbol+'&apikey='+api_key
    r = requests.get(url)
    r = r.json()
    data = r['quarterlyReports']
    df = pd.json_normalize(data)
    df.set_index('fiscalDateEnding',drop=True,inplace=True)
    df.index = pd.to_datetime(df.index)
    df = df.replace('None',0).drop('reportedCurrency',axis=1).astype(float).sort_index()
    df=df[['totalRevenue','operatingIncome','ebitda','netIncome']]
    df.columns=pl_japa
    return df

def EPS(symbol,api_key):
    url='https://www.alphavantage.co/query?function=EARNINGS&symbol='+symbol+'&apikey='+api_key
    r = requests.get(url)
    r = r.json()
    data = r['quarterlyEarnings']
    df_EPS = pd.json_normalize(data)
    df_EPS.set_index('fiscalDateEnding',drop=True,inplace=True)
    df_EPS.index = pd.to_datetime(df_EPS.index)
    df_EPS = df_EPS.replace('None',0)
    df_EPS[df_EPS.columns[1:]].astype(float).sort_index()
    df_EPS.columns=[['決算日','結果EPS','予想EPS','コンセンサス差','％']]
    return df_EPS

In [31]:
test=FR('AAPL',api_key)
test

                            収益          営業利益        EBITDA           純利益
fiscalDateEnding
2016-12-31        7.835100e+10  2.335900e+10  2.769200e+10  1.789100e+10
2017-03-31        5.289600e+10  1.409700e+10  1.754600e+10  1.102900e+10
2017-06-30        4.540800e+10  1.076800e+10  1.426400e+10  8.717000e+09
2017-09-30        5.257900e+10  1.312000e+10  1.706700e+10  1.071400e+10
2017-12-31        8.829300e+10  2.627400e+10  3.050900e+10  2.006500e+10
2018-03-31        6.113700e+10  1.589400e+10  1.969900e+10  1.382200e+10
2018-06-30        5.326500e+10  1.261200e+10  1.679500e+10  1.151900e+10
2018-09-30        6.290000e+10  1.611800e+10  2.004300e+10  1.412500e+10
2018-12-31        8.342000e+10  2.334600e+10  2.819100e+10  1.996500e+10
2019-03-31        5.700500e+10  1.341500e+10  1.784300e+10  1.156100e+10
2019-06-30        5.294300e+10  1.154400e+10  1.571000e+10  1.004400e+10
2019-09-30        6.404000e+10  1.562500e+10  2.011600e+10  1.368600e+10
2019-12-31        9.103400e+10  2.556900e+10  2.951900e+10  2.223600e+10
2020-03-31        5.755600e+10  1.285300e+10  1.667800e+10  1.124900e+10
2020-06-30        5.898800e+10  1.309100e+10  1.658600e+10  1.125300e+10
2020-09-30        6.469800e+10  1.477500e+10  1.823700e+10  1.267300e+10
2020-12-31        1.108010e+11  3.353400e+10  3.688300e+10  2.875500e+10
2021-03-31        8.891400e+10  2.750300e+10  3.147800e+10  2.363000e+10
2021-06-30        8.076900e+10  2.412600e+10  2.786600e+10  2.174400e+10
2021-09-30        8.268800e+10  2.378600e+10  2.690900e+10  2.055100e+10

In [47]:
test2=EPS('AAPL',api_key)
test2

,reportedDate,reportedEPS,estimatedEPS,surprise,surprisePercentage
fiscalDateEnding,,,,,
2021-09-30,2021-10-28,1.24,1.238,0.002,0.1616
2021-06-30,2021-07-27,1.3,1.0143,0.2857,28.1672
2021-03-31,2021-04-28,1.4,0.9888,0.4112,41.5858
2020-12-31,2021-01-27,1.68,1.4158,0.2642,18.6608
2020-09-30,2020-10-29,0.73,0.6987,0.0313,4.4797
...,...,...,...,...,...
1997-03-31,1997-04-16,-0.05,-0.04,-0.01,-25
1996-12-31,1997-01-15,-0.03,-0.02,-0.01,-50
1996-09-30,1996-10-16,0.0018,-0.01,0.0118,118
1996-06-30,1996-07-17,-0.02,-0.04,0.02,50
1996-03-31,1996-04-17,-0.07,-0.05,-0.02,-40

In [16]:
test.columns

Index(['grossProfit', 'totalRevenue', 'costOfRevenue',
       'costofGoodsAndServicesSold', 'operatingIncome',
       'sellingGeneralAndAdministrative', 'researchAndDevelopment',
       'operatingExpenses', 'investmentIncomeNet', 'netInterestIncome',
       'interestIncome', 'interestExpense', 'nonInterestIncome',
       'otherNonOperatingIncome', 'depreciation',
       'depreciationAndAmortization', 'incomeBeforeTax', 'incomeTaxExpense',
       'interestAndDebtExpense', 'netIncomeFromContinuingOperations',
       'comprehensiveIncomeNetOfTax', 'ebit', 'ebitda', 'netIncome'],
      dtype='object')

,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.125456,0.148756,0.157904,0.15963,0.157114
Normalized EBITDA,26050000000.0,31216000000.0,38932000000.0,27759000000.0,25881000000.0
Net Income From Continuing Operation Net Minority Interest,19881000000.0,24160000000.0,29998000000.0,20721000000.0,19442000000.0
Reconciled Depreciation,3052000000.0,2898000000.0,2916000000.0,2865000000.0,2805000000.0
Reconciled Cost Of Revenue,45384000000.0,52860000000.0,66822000000.0,52051000000.0,47074000000.0
EBIT,22998000000.0,28318000000.0,36016000000.0,24894000000.0,23076000000.0
Net Interest Income,-18000000.0,-12000000.0,-135000000.0,-74000000.0,3000000.0
Interest Expense,998000000.0,930000000.0,1003000000.0,827000000.0,719000000.0
Interest Income,980000000.0,918000000.0,868000000.0,753000000.0,722000000.0
Normalized Income,19881000000.0,24160000000.0,29998000000.0,20721000000.0,19442000000.0
Net Income From Continuing And Discontinued Operation,19881000000.0,24160000000.0,29998000000.0,20721000000.0,19442000000.0
Total Expenses,58799000000.0,66518000000.0,81138000000.0,65252000000.0,59883000000.0
Total Operating Income As Reported,22998000000.0,28318000000.0,36016000000.0,24894000000.0,23076000000.0
Diluted Average Shares,15775021000.0,15847050000.0,15955718000.0,16118465000.0,16262203000.0
Basic Average Shares,15697614000.0,15787154000.0,15892723000.0,16030382000.0,16162945000.0
Diluted EPS,1.26,1.52,1.88,1.29,1.2
Basic EPS,1.27,1.53,1.89,1.29,1.2
Diluted NI Availto Com Stockholders,19881000000.0,24160000000.0,29998000000.0,20721000000.0,19442000000.0
Net Income Common Stockholders,19881000000.0,24160000000.0,29998000000.0,20721000000.0,19442000000.0
Net Income,19881000000.0,24160000000.0,29998000000.0,20721000000.0,19442000000.0
Net Income Including Noncontrolling Interests,19881000000.0,24160000000.0,29998000000.0,20721000000.0,19442000000.0
Net Income Continuous Operations,19881000000.0,24160000000.0,29998000000.0,20721000000.0,19442000000.0
Tax Provision,2852000000.0,4222000000.0,5625000000.0,3936000000.0,3624000000.0
Pretax Income,22733000000.0,28382000000.0,35623000000.0,24657000000.0,23066000000.0
Other Income Expense,-265000000.0,64000000.0,-393000000.0,-237000000.0,-10000000.0
Other Non Operating Income Expenses,-265000000.0,64000000.0,-393000000.0,-237000000.0,-10000000.0
Net Non Operating Interest Income Expense,-18000000.0,-12000000.0,-135000000.0,-74000000.0,3000000.0
Interest Expense Non Operating,998000000.0,930000000.0,1003000000.0,827000000.0,719000000.0
Interest Income Non Operating,980000000.0,918000000.0,868000000.0,753000000.0,722000000.0
Operating Income,22998000000.0,28318000000.0,36016000000.0,24894000000.0,23076000000.0
Operating Expense,13415000000.0,13658000000.0,14316000000.0,13201000000.0,12809000000.0
Research And Development,7442000000.0,7457000000.0,7709000000.0,6761000000.0,6797000000.0
Selling General And Administration,5973000000.0,6201000000.0,6607000000.0,6440000000.0,6012000000.0
Gross Profit,36413000000.0,41976000000.0,50332000000.0,38095000000.0,35885000000.0
Cost Of Revenue,45384000000.0,52860000000.0,66822000000.0,52051000000.0,47074000000.0
Total Revenue,81797000000.0,94836000000.0,117154000000.0,90146000000.0,82959000000.0
Operating Revenue,81797000000.0,94836000000.0,117154000000.0,90146000000.0,82959000000.0